<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#A-Quick-Tour-of-TensorFlow" data-toc-modified-id="A-Quick-Tour-of-TensorFlow-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>A Quick Tour of TensorFlow</a></span></li><li><span><a href="#Using-TensorFlow-like-NumPy" data-toc-modified-id="Using-TensorFlow-like-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Using TensorFlow like NumPy</a></span><ul class="toc-item"><li><span><a href="#Tensors-and-Operations" data-toc-modified-id="Tensors-and-Operations-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Tensors and Operations</a></span></li><li><span><a href="#Tensors-and-NumPy" data-toc-modified-id="Tensors-and-NumPy-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Tensors and NumPy</a></span></li><li><span><a href="#Type-Conversions" data-toc-modified-id="Type-Conversions-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Type Conversions</a></span></li><li><span><a href="#Variables" data-toc-modified-id="Variables-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Variables</a></span></li><li><span><a href="#Other-Data-Structures" data-toc-modified-id="Other-Data-Structures-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Other Data Structures</a></span></li></ul></li><li><span><a href="#Customizing-Models-and-Training-Algorithms" data-toc-modified-id="Customizing-Models-and-Training-Algorithms-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Customizing Models and Training Algorithms</a></span><ul class="toc-item"><li><span><a href="#Custom-Loss-Functions" data-toc-modified-id="Custom-Loss-Functions-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Custom Loss Functions</a></span></li><li><span><a href="#Saving-and-Loading-Models-That-Contains-Custom-Components" data-toc-modified-id="Saving-and-Loading-Models-That-Contains-Custom-Components-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Saving and Loading Models That Contains Custom Components</a></span></li><li><span><a href="#Custom-Activation-Functions,-Initializers,-Regularizers,-and-Constraints" data-toc-modified-id="Custom-Activation-Functions,-Initializers,-Regularizers,-and-Constraints-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Custom Activation Functions, Initializers, Regularizers, and Constraints</a></span></li><li><span><a href="#Custom-Metrics" data-toc-modified-id="Custom-Metrics-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Custom Metrics</a></span></li><li><span><a href="#Custom-Layers" data-toc-modified-id="Custom-Layers-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Custom Layers</a></span></li><li><span><a href="#Custom-Models" data-toc-modified-id="Custom-Models-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Custom Models</a></span></li><li><span><a href="#Losses-and-Metrics-Based-on-Model-Internals" data-toc-modified-id="Losses-and-Metrics-Based-on-Model-Internals-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Losses and Metrics Based on Model Internals</a></span></li><li><span><a href="#Computing-Gradients-Using-Autodiff" data-toc-modified-id="Computing-Gradients-Using-Autodiff-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>Computing Gradients Using Autodiff</a></span></li><li><span><a href="#Custom-Training-Loops" data-toc-modified-id="Custom-Training-Loops-3.9"><span class="toc-item-num">3.9&nbsp;&nbsp;</span>Custom Training Loops</a></span></li></ul></li><li><span><a href="#TensorFlow-Functions-and-Graphs" data-toc-modified-id="TensorFlow-Functions-and-Graphs-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>TensorFlow Functions and Graphs</a></span><ul class="toc-item"><li><span><a href="#AutoGraph-and-Tracing" data-toc-modified-id="AutoGraph-and-Tracing-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>AutoGraph and Tracing</a></span></li><li><span><a href="#TF-Function-Rules" data-toc-modified-id="TF-Function-Rules-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>TF Function Rules</a></span></li></ul></li></ul></div>

## A Quick Tour of TensorFlow

High-level DL APIs
- tf.keras
- tf.estimator

Low-level DL APIs
- tf.nn
- tf.losses
- tf.metrics
- tf.optimizers
- tf.train
- tf.initializers

Autodiff
- tf.GradientTape
- tf.gradients()

I/O and preprocessing
- tf.data
- tf.feature_column
- tf.audio
- tf.image
- tf.io
- tf.queue

Visualization with TensorBoard
- tf.summary

Deployment and optimization
- tf.distribute
- tf.saved_model
- tf.autograph
- tf.graph_util
- tf.lite
- tf.quantization
- tf.tpu
- tf.xla

Special data structures
- tf.lookup
- tf.nest
- tf.ragged
- tf.sets
- tf.sparse
- tf.strings

Mathematics, including linear algebraand signal processing
- tf.math
- tf.linalg
- tf.signal
- tf.random
- tf.bitwise

Miscellaneous
- tf.compat
- tf.config

& more

## Using TensorFlow like NumPy

In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf
from tensorflow import keras

### Tensors and Operations

In [3]:
tf.constant([[1,2,3.], [3,4,5]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)>

In [4]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
t = tf.constant([[1.,2.,3.,], [4.,5.,6.]])

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.float32

In [9]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [13]:
t[:, 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [14]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [16]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [20]:
t @ tf.transpose(t) # @ is matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [21]:
# OR
tf.matmul(t, tf.transpose(t))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

### Tensors and NumPy

In [28]:
a = np.array([2.,4.,5.])
tf.constant(a, dtype=tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 5.], dtype=float32)>

In [25]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [29]:
tf.square(a.astype(np.float32))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 4., 16., 25.], dtype=float32)>

In [27]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

### Type Conversions

In [33]:
from tensorflow.errors import InvalidArgumentError

In [36]:
try:
    tf.constant(2.) + tf.constant(1)
except InvalidArgumentError:
    print('TF do not perform any type conversion automatically')
    
tf.constant(2) + tf.constant(1)

TF do not perform any type conversion automatically


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [42]:
t2 = tf.constant(40, dtype=tf.float64)
try:
    tf.constant(2.0) + t2
except InvalidArgumentError:
    print("float32 cannot add float64 automatically")

float32 cannot add float64 automatically


In [43]:
tf.constant(2.) + tf.cast(t2, dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

### Variables

Can be mutable

In [57]:
v = tf.Variable([[1.,2.,3.], [4.,5.,6.]], dtype=tf.float32)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [58]:
v.assign_add(np.ones((2,3)))

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [59]:
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4.,  6.,  8.],
       [10., 12., 14.]], dtype=float32)>

In [60]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4., 42.,  8.],
       [10., 12., 14.]], dtype=float32)>

In [62]:
v[:, 2].assign([0., 1.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4., 42.,  0.],
       [10., 12.,  1.]], dtype=float32)>

In [63]:
v.scatter_nd_update(indices=[[0, 0], [1,2]], updates=[100, 200])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [ 10.,  12., 200.]], dtype=float32)>

### Other Data Structures

In [ ]:
# spare tensor: efficiently represent tensors containing mostly zeros.
# tf.sparse contains operations for sparse tensors
tf.SparseTensor

# tensor array: lists of tensors. All tensors must have the same shape and data type.
tf.TensorArray

# ragged tensors: represents static lists of lists of tensors, every tensor has the same shape and data type.
# tf.ragged contains operations for ragged tensors
tf.RaggedTensor

# strinf tensors
tf.string

# sets
tf.sets

# queues
tf.queue

## Customizing Models and Training Algorithms

 ### Custom Loss Functions

In [ ]:
keras.losses.Huber()

```
loss = 0.5 * x^2                  if |x| <= d
loss = 0.5 * d^2 + d * (|x| - d)  if |x| > d

where x is y_true - y_pred;
d is delta, a hyperparameter 
```

In [3]:
# implement Huber loss
def huber_fn(y_true, y_pred):
    delta = 1.0
    error = y_true - y_pred
    is_small_error = tf.abs(error) <= delta
    squared_loss = tf.square(error) * 0.5
    linear_loss = 0.5 * delta**2 + delta * (tf.abs(error) - delta)
    return tf.where(is_small_error, squared_loss, linear_loss)

In [ ]:
model.compile(loss=huber_fn, optimizer='nadam')
model.fit(X_train, y_train)

### Saving and Loading Models That Contains Custom Components

In [ ]:
model = keras.models.load_model("path_to_model", custom_objects={'huber_fn': huber_fn})

In [4]:
# different threshold
def create_huber(delta=1.0):
    def huber_fn(y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) <= delta
        squared_loss = tf.square(error) * 0.5
        linear_loss = 0.5 * delta**2 + delta * (tf.abs(error) - delta)
        return tf.where(is_small_error, squared_loss, linear_loss)
    return huber_fn

In [ ]:
model.compile(loss=create_huber(3.0), optimizer='nadam')

In [ ]:
model = keras.models.load_model('path_to_model', custom_objects={'huber_fn': create_huber(3.0)})

In [5]:
## another way is to use subclass
class HuberLoss(keras.losses.Loss):
    def __init__(self, delta=1.0, **kwargs):
        self.delta = delta
        super(HuberLoss, self).__init__(**kwargs)
    def call(self, y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) <= delta
        squared_loss = tf.square(error) * 0.5
        linear_loss = 0.5 * delta**2 + delta * (tf.abs(error) - delta)
        return tf.where(is_small_error, squared_loss, linear_loss)
    def get_config(self):
        base_config = super(HuberLoss, self).get_config()
        return {**base_config, "delta": self.delta}

In [ ]:
model.compile(loss=HuberLoss(2.), optimizer='nadam')

In [ ]:
model = keras.models.load_model('path_to_model', custom_objects={'HuberLoss': HuberLoss})

### Custom Activation Functions, Initializers, Regularizers, and Constraints

In [6]:
def my_softplus(z):
    return tf.math.log(tf.exp(z) + 1.0)

In [7]:
# `stddev = sqrt(2 / (fan_in + fan_out))`
def my_glorot_initializer(shape, dtype=tf.float32):
    stddev = tf.sqrt(2.0 / (shape[0] + shape[1]))
    return tf.random.normal(shape, stddev=stddev, dtype=dtype)

In [8]:
def my_l1_regularizer(weights):
    alpha = 0.01
    return tf.reduce_sum(tf.math.abs(alpha * weights))

In [9]:
# return value is just tf.nn.relu(weights)
def my_positive_weights(weights):
    return tf.where(weights<0, tf.zeros_like(weights), weights)

In [10]:
layer = keras.layers.Dense(30, 
                           activation=my_softplus, 
                           kernel_initializer=my_glorot_initializer,
                           kernel_regularizer=my_l1_regularizer,
                           kernel_constraint=my_positive_weights)

If want to save the hyperparameter in customized components, need to subclass

In [11]:
class MyL1Regularizer(keras.regularizers.Regularizer):
    def __init__(self, alpha, **kwargs):
        self.alpha = alpha
        super(MyL1Regularizer, self).__init__(**kwargs)
    def __call__(self, weights):
        return tf.reduce_sum(tf.math.abs(self.alpha * weights))
    def get_config(self):
        base_config = super(MyL1Regularizer, self).get_config()
        return {**base_config, "alpha": self.alpha}

NOTE: initializer, regularizer, constraint implement \__call__(), while for layers, losses, activation functions, models is call() instead

### Custom Metrics

In [ ]:
model.compile(loss='mse', optimizer='nadam', metrics=[create_huber(2.0)])

Streaming metric(stateful metric):

In [12]:
precision = keras.metrics.Precision()

In [25]:
precision([0,1,1,1,0,1,0,1], [1,1,0,1,0,1,0,1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [26]:
precision.variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>]

In [27]:
precision([0,1,0], [1,0,1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.5714286>

In [28]:
precision.variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>]

In [23]:
precision.reset_states()

In [22]:
keras.metrics.Recall().variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'false_negatives:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

Customized HuberMetrics subclass Metrc

In [32]:
class HuberMetric(keras.metrics.Metric):
    def __init__(self, delta=1.0, **kwargs):
        super(HuberMetric, self).__init__(**kwargs)
        self.delta = delta
        self.huber_fn = huber_fn(self.delta)
        self.total = self.add_weight("total", initializer="zeros")
        self.conut = self.add_weight("count", initializer="zeros")
    def update_state(self, y_true, y_pred, sample_weight=None):
        metric = self.huber_fn(y_true, y_pred)
        self.total.assign_add(tf.reduce_sum(metric))
        self.count.assign_add(tf.cast(tf.size(y_true), tf.float32))
    def result(self):
        return self.total / self.count
    def get_config(self):
        base_config = super(HuberMetric, self).get_config()
        return {**base_config, "delta": self.delta}

### Custom Layers

In [33]:
# layers without parameters
# use keras.layers.Lambda to wrap
# e.g.
exponential_layer = keras.layers.Lambda(lambda x: tf.exp(x))

In [49]:
a = tf.random.uniform((3,5))

In [50]:
a

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.9039606 , 0.22642279, 0.31175542, 0.78124166, 0.49105382],
       [0.6626599 , 0.30204666, 0.36431026, 0.33980227, 0.7871053 ],
       [0.4914937 , 0.27795398, 0.5386164 , 0.27939844, 0.84706664]],
      dtype=float32)>

In [51]:
exponential_layer(a)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[2.469364 , 1.2541058, 1.3658206, 2.1841826, 1.6340373],
       [1.9399455, 1.3526244, 1.439521 , 1.4046699, 2.1970274],
       [1.6347562, 1.3204254, 1.7136343, 1.322334 , 2.332794 ]],
      dtype=float32)>

Dense Layer

In [52]:
class MyDense(keras.layers.Layer):
    def __init__(self, units, activation=None, **kwargs):
        super(MyDense, self).__init__(**kwargs)
        self.units = units
        self.activation = keras.activations.get(activation)
    def build(self, batch_input_shape):
        self.kernel = self.add_weight(
            name='kernel',
            shape=[batch_input_shape[-1], self.units],
            initializer="glorot_normal"
        )
        self.bias = self.add_weight(
            name='bias',
            shape=[self.units],
            initializer='zeros'
        )
        super(MyDense, self).build(batch_input_shape) # must be at the end
    def call(self, X):
        return self.activation(X @ self.weights + self.bias)
    def compute_output_shape(self, batch_input_shape): # return tf.TensorShape
        return tf.TensorShape(batch_input_shape.as_list()[:-1] + [self.units])
    def get_config(self):
        base_config = super(MyDense, self).get_config()
        return {**base_config, "units": self.units, "activation": keras.activations.serialize(self.activation)}

Different behavor during training and testing

In [53]:
class MyGaussianNoise(keras.layers.Layer):
    def __init__(self, stddev, **kwargs):
        super(MyGaussianNoise, self).__init__(**kwargs)
        self.stddev = stddev
    def call(self, X, training=None):
        # add Gaussian noise during training
        if training:
            noise = tf.random.normal(tf.shape(X), stddev=self.stddev)
            return X + noise
        else:
            return X
    def compute_output_shape(self, batch_input_shape):
        return batch_input_shape

### Custom Models

In [54]:
class ResidualBlock(keras.layers.Layer):
    def __init__(self, n_layers, n_neurons, **kwargs):
        super(ResidualBlock, self).__init__(**kwargs)
        self.hidden = [keras.layers.Dense(n_neurons, activation='relu', 
                                          kernel_initializer='he_normal') 
                       for _ in range(n_layers)]
        def call(self, X):
            Z = X
            for layer in self.hidden:
                Z = layer(Z)
            return Z + X

In [55]:
class ResidualRegressor(keras.Model):
    def __init__(self, output_dim, **kwargs):
        super(ResidualRegressor, self).__init__(**kwargs)
        self.hidden1 = keras.layers.Dense(30, activation='elu', kernel_initialier='he_normal')
        self.block1 = ResidualBlock(2, 30)
        self.block2 = ResidualBlock(2, 30)
        self.out = keras.layers.Dense(output_dim)
    def call(self, inputs):
        Z = self.hidden1(inputs)
        for _ in range(3 + 1):
            Z = self.block1(Z)
        Z = self.block2(Z)
        return self.out(Z)

### Losses and Metrics Based on Model Internals

Custom model with a custom reconstruction loss

In [56]:
class ReconstructingRegressor(keras.Model):
    def __init__(self, output_dim, **kwargs):
        super(ReconstructingRegressor, self).__init__(**kwargs)
        self.hidden = [keras.layers.Dense(30, activation='selu', 
                                          kernel_initializer='lecun_normal') 
                       for _ in range(5)]
        self.out = keras.layers.Dense(output_dim)
    def build(self, batch_input_shape):
        n_inputs = batch_input_shape[-1]
        self.reconstruct = keras.layers.Dense(n_inputs)
        super(ReconstructingRegressor, self).build(batch_input_shape)
    
    def call(self, inputs):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        reconstruction = self.reconstruct(Z)
        recon_loss = tf.reduce_mean(tf.square(reconstruction - inputs))
        self.add_loss(0.05 * recon_loss)
        return self.out(Z)

### Computing Gradients Using Autodiff

In [58]:
# simple function to illustrate autodiff
def f(w1, w2):
    return 3 * w1**2 + 2 * w1*w2

In [61]:
w1, w2 = tf.Variable(5.0), tf.Variable(3.)
with tf.GradientTape() as tape:
    z = f(w1, w2)
gradient = tape.gradient(z, [w1, w2])
gradient

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

Keep tape persisitent

In [63]:
with tf.GradientTape(persistent=True) as tape:
    z = f(w1, w2)

In [64]:
tape.gradient(z, [w1, w2])

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [65]:
tape.gradient(z, [w1])

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>]

In [66]:
del tape

tape will only watch the variabels, but we can force it to watch any tensors as we want

In [67]:
c1, c2 = tf.constant(5.), tf.constant(3.)
with tf.GradientTape() as tape:
    z = f(w1, w2)

In [68]:
tape.gradient(z, [c1, c2])

[None, None]

In [74]:
with tf.GradientTape() as tape:
    tape.watch(c1)
    tape.watch(c2)
    z = f(c1, c2)

In [75]:
tape.gradient(z, [c1 ,c2])

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

Stop gradient is specific part

In [80]:
def f(w1, w2):
    return 3 * w1**2 + tf.stop_gradient(2 * w1 * w2)

In [81]:
with tf.GradientTape() as tape:
    z = f(w1, w2)

In [82]:
tape.gradient(z, [w1, w2])

[<tf.Tensor: shape=(), dtype=float32, numpy=30.0>, None]

Some numerical problem in autodiff

In [83]:
x = tf.Variable(100.)
with tf.GradientTape() as tape:
    z = my_softplus(x)

In [84]:
tape.gradient(z, x)

<tf.Tensor: shape=(), dtype=float32, numpy=nan>

In [91]:
# use custom_gradient to solve the problem
@tf.custom_gradient
def my_better_softplus(z):
    exp = tf.exp(z)
    def my_softplus_gradient(grad):
        """grad from previous backpropogate gradients
        """
        return grad / (1 + 1/exp)
    return tf.math.log(exp + 1), my_softplus_gradient

In [92]:
with tf.GradientTape() as tape:
    z = my_better_softplus(x)

In [93]:
tape.gradient(z, x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

### Custom Training Loops

In [187]:
l2_reg = keras.regularizers.l2(0.05)
model = keras.models.Sequential([
    keras.layers.Dense(30, activation='elu', kernel_initializer='he_normal', kernel_regularizer=l2_reg),
    keras.layers.Dense(1, kernel_regularizer=l2_reg)
])

In [188]:
def random_barch(X, y, batch_size=32):
    idx = np.random.randint(len(X), size=batch_size)
    return X[idx], y[idx]

In [189]:
def print_status_bar(iteration, total, loss, metrics=None):
    metrics = " - ".join([f'{m.name}: {m.result():.4f}' for m in [loss]+(metrics or [])])
    end = "" if iteration < total else "\n"
    print(f"\r{iteration}/{total} - " + metrics, end=end)

In [190]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(housing.data, housing.target)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [191]:
n_epoch = 5
batch_size = 32
n_steps = len(X_train) // batch_size
optimizer = keras.optimizers.Nadam(lr=0.01)
loss_fn = keras.losses.mean_squared_error
mean_loss = keras.metrics.Mean()
metrics = [keras.metrics.MeanAbsoluteError()]

In [196]:
for epoch in range(1, n_epoch+1):
    print(f"Epoch {epoch}/{n_epoch}")
    for step in range(1, n_steps+1):
        X_batch, y_batch = random_barch(X_train, y_train)
        with tf.GradientTape() as tape:
            # predict
            y_pred = model(X_batch, training=True)
            
            # losses
            main_loss = tf.reduce_mean(loss_fn(y_batch, y_pred)) # model MSE loss
            all_loss_list = [main_loss] + model.losses # MSE loss + layer1 l2 loss + layer2 l2 loss
            loss = tf.add_n(all_loss_list) # sum up all losses
            
        # calcualte and update gradients
        gradients = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))

        # calculate metrics
        mean_loss(loss) # mean loss(MSE+l2_1+l2_2) average batch
        for metric in metrics:
            metric(y_batch, y_pred)
        print_status_bar(step*batch_size, len(y_train), mean_loss, metrics)
    # print out the total mean_loss
    print_status_bar(len(y_train), len(y_train), mean_loss, metrics)
    # finish epoch, reset all metrics
    for metric in [mean_loss] + metrics:
        metric.reset_states()

Epoch 1/5
11610/11610 - mean: 1.3744 - mean_absolute_error: 0.9170
Epoch 2/5
11610/11610 - mean: 1.3467 - mean_absolute_error: 0.9002
Epoch 3/5
11610/11610 - mean: 1.3756 - mean_absolute_error: 0.9131
Epoch 4/5
11610/11610 - mean: 1.3368 - mean_absolute_error: 0.9015
Epoch 5/5
11610/11610 - mean: 1.3675 - mean_absolute_error: 0.9094


In [197]:
# code snipet for weights&bias constraint
for variable in model.variables:
    if variable.constraint is not None:
        variable.assign(variable.constraint(variable))

## TensorFlow Functions and Graphs

In [198]:
def cube(x):
    return x**3

In [201]:
cube(tf.constant(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [203]:
# use tf.function() to convert this Python function to a TensorFlow Function
tf_cube = tf.function(cube)

In [209]:
tf_cube(tf.constant(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [210]:
# or we can use decorator
@tf.function
def tf_cube(x):
    return x**3

In [212]:
tf_cube.python_function(3)

27

### AutoGraph and Tracing

### TF Function Rules